services:
  - type: web
    name: chipactli
    env: node
    buildCommand: npm install && npm --prefix frontend install && npm --prefix frontend run prepare-assets && npm --prefix frontend run build && npm --prefix backend install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_DIR
        value: /opt/render/data/backend
      - key: BACKUP_INTERVAL_HOURS
        value: "1"
      - key: BACKUP_INITIAL_DELAY_SEC
        value: "30"
    # Disco persistente para que las bases de datos no se borren
    disk:
      name: chipactli-data
      mountPath: /opt/render/data
      sizeGB: 1
